import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: "#FFFFFF" },
  screen: { flex: 1, backgroundColor: "#FFFFFF", paddingHorizontal: 28 },
  profileTop: { flexGrow: 1, paddingTop: 20, alignItems: "center" },
  backButton: { alignSelf: "flex-start", padding: 4, marginBottom: 20 },
  backText: { color: "#128C7E", fontSize: 30 },
  profileTitle: {
    color: "#111B21",
    fontSize: 24,
    fontWeight: "700",
    marginBottom: 8,
  },
  profileBody: {
    color: "#667781",
    textAlign: "center",
    fontSize: 14,
    lineHeight: 21,
    marginBottom: 16,
  },
  modeSwitch: { alignSelf: "center", paddingVertical: 8, marginBottom: 12 },
  modeSwitchText: { color: "#128C7E", fontSize: 14, fontWeight: "600" },
  avatarButton: {
    width: 112,
    height: 112,
    borderRadius: 56,
    backgroundColor: "#D9FDD3",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 30,
  },
  avatarText: { color: "#128C7E", fontSize: 36, fontWeight: "700" },
  cameraBadge: {
    position: "absolute",
    right: 0,
    bottom: 0,
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: "#00A884",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 3,
    borderColor: "#FFFFFF",
  },
  cameraText: { color: "#FFFFFF", fontSize: 16 },
  label: {
    alignSelf: "stretch",
    color: "#128C7E",
    fontSize: 12,
    marginBottom: 6,
  },
  input: {
    alignSelf: "stretch",
    borderBottomWidth: 2,
    borderBottomColor: "#00A884",
    color: "#111B21",
    fontSize: 17,
    paddingVertical: 9,
    marginBottom: 16,
  },
  errorText: {
    alignSelf: "stretch",
    color: "#B3261E",
    fontSize: 13,
    marginBottom: 12,
  },
  profileButton: { alignSelf: "stretch", paddingTop: 8 },
  primaryButton: {
    height: 50,
    borderRadius: 25,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#00A884",
    marginBottom: 16,
  },
  disabledButton: { opacity: 0.65 },
  primaryButtonText: { color: "#FFFFFF", fontSize: 16, fontWeight: "700" },
});
