import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: "#FFFFFF" },
  screen: { flex: 1, backgroundColor: "#FFFFFF", paddingHorizontal: 28 },
  language: {
    alignSelf: "flex-end",
    color: "#667781",
    fontSize: 14,
    marginTop: 12,
  },
  hero: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingBottom: 35,
  },
  logoCircle: {
    width: 116,
    height: 116,
    borderRadius: 58,
    backgroundColor: "#25D366",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 34,
  },
  logoBubble: {
    width: 68,
    height: 54,
    borderRadius: 28,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    transform: [{ rotate: "-8deg" }],
  },
  logoText: { color: "#128C7E", fontSize: 28, fontWeight: "800" },
  title: {
    color: "#111B21",
    fontSize: 28,
    fontWeight: "700",
    marginBottom: 14,
  },
  body: {
    color: "#667781",
    textAlign: "center",
    fontSize: 15,
    lineHeight: 22,
    maxWidth: 310,
  },
  privacy: {
    color: "#667781",
    textAlign: "center",
    fontSize: 12,
    lineHeight: 18,
    marginBottom: 16,
  },
  privacyLink: { color: "#128C7E", fontWeight: "600" },
  primaryButton: {
    height: 50,
    borderRadius: 25,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#00A884",
    marginBottom: 16,
  },
  primaryButtonText: { color: "#FFFFFF", fontSize: 16, fontWeight: "700" },
  version: {
    textAlign: "center",
    color: "#8696A0",
    fontSize: 11,
    marginBottom: 14,
  },
  profileTop: { paddingTop: 28, alignItems: "center" },
  backButton: { alignSelf: "flex-start", padding: 4, marginBottom: 20 },
  backText: { color: "#128C7E", fontSize: 30 },
  profileTitle: {
    color: "#111B21",
    fontSize: 24,
    fontWeight: "700",
    marginBottom: 8,
  },
  profileBody: {
    color: "#667781",
    textAlign: "center",
    fontSize: 14,
    lineHeight: 21,
    marginBottom: 28,
  },
  avatarButton: {
    width: 112,
    height: 112,
    borderRadius: 56,
    backgroundColor: "#D9FDD3",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 30,
  },
  avatarText: { color: "#128C7E", fontSize: 36, fontWeight: "700" },
  cameraBadge: {
    position: "absolute",
    right: 0,
    bottom: 0,
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: "#00A884",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 3,
    borderColor: "#FFFFFF",
  },
  cameraText: { color: "#FFFFFF", fontSize: 16 },
  label: {
    alignSelf: "stretch",
    color: "#128C7E",
    fontSize: 12,
    marginBottom: 6,
  },
  input: {
    alignSelf: "stretch",
    borderBottomWidth: 2,
    borderBottomColor: "#00A884",
    color: "#111B21",
    fontSize: 17,
    paddingVertical: 9,
    marginBottom: 26,
  },
  profileButton: { alignSelf: "stretch", marginTop: "auto" },
});
