import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  conversation: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    paddingVertical: 11,
    paddingHorizontal: 16,
    minHeight: 72,
    borderBottomWidth: 1,
    borderBottomColor: "#E9EDEF",
  },
  avatar: {
    width: 50,
    height: 50,
    borderRadius: 25,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
    marginRight: 13,
  },
  avatarText: { color: "#FFFFFF", fontSize: 13, fontWeight: "700" },
  onlineDot: {
    width: 11,
    height: 11,
    borderRadius: 6,
    backgroundColor: "#8DAF70",
    borderWidth: 2,
    borderColor: "#FFFFFF",
    position: "absolute",
    right: -2,
    bottom: -2,
  },
  conversationCopy: { flex: 1, minWidth: 0 },
  nameLine: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    marginBottom: 4,
  },
  name: { color: "#111B21", fontSize: 16, fontWeight: "500" },
  groupLabel: {
    color: "#9C958A",
    fontSize: 10,
    fontWeight: "600",
    textTransform: "uppercase",
  },
  preview: { color: "#667781", fontSize: 13 },
  unreadPreview: { color: "#3B4A51", fontWeight: "600" },
  conversationMeta: {
    alignItems: "flex-end",
    alignSelf: "stretch",
    justifyContent: "space-between",
    paddingVertical: 2,
    marginLeft: 8,
  },
  time: { color: "#667781", fontSize: 11 },
  unreadTime: { color: "#00A884", fontWeight: "500" },
  unreadBadge: {
    width: 19,
    height: 19,
    borderRadius: 10,
    backgroundColor: "#25D366",
    alignItems: "center",
    justifyContent: "center",
  },
  unreadText: { color: "#FFF", fontSize: 10, fontWeight: "700" },
});
